### ISSUE TITLE
Installation on Ubuntu fails at 'rake db:schema:load'

### ISSUE THREAD

**Issue by vaMuchenje** [jcs/lobsters#275]
Here is the end part of the trace:

`
```
/usr/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'                                                                                                
/usr/lib/ruby/2.2.0/tsort.rb:345:in `each'                                                                                                                                      
/usr/lib/ruby/2.2.0/tsort.rb:345:in `call'                                                                                                                                      
/usr/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'                                                                                                         
/usr/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'                                                                                                                                
/usr/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'                                                                                                                                
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'                                                                                    
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'                                                                                          
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'                                                                                              
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'                                                                                           
/home/codio/workspace/unu/config/environment.rb:5:in `<top (required)>'                                                                                                         
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'                                                                               
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'                                                                      
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'                                                                       
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'                                                                               
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'                                                                                 
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'                                                                            
/usr/lib/ruby/2.2.0/rake/task.rb:240:in `call'                                                                                                                                  
/usr/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'                                                                                                                      
/usr/lib/ruby/2.2.0/rake/task.rb:235:in `each'                                                                                                                                  
/usr/lib/ruby/2.2.0/rake/task.rb:235:in `execute'                                                                                                                               
/usr/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'                                                                                                       
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'                                                                                                                         
/usr/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'                                                                                                                
/usr/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'                                                                                                         
/usr/lib/ruby/2.2.0/rake/task.rb:199:in `each'                                                                                                                                  
/usr/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'                                                                                                                  
/usr/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'                                                                                                       
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'                                                                                                                         
/usr/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'                                                                                                                
/usr/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'                                                                                                                                
/usr/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'                                                                                                                    
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'                                                                                                  
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `each'                                                                                                                           
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'                                                                                                             
/usr/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'                                                                                                               
/usr/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'                                                                                                                      
/usr/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'                                                                                                                    
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'                                                                                                    
/usr/lib/ruby/2.2.0/rake/application.rb:75:in `run'                                                                                                                             
/usr/bin/rake:33:in `<main>'                                                                                                                                                    
Tasks: TOP => db:migrate => environment    
```
`

**Comment by jcs** [comment]
From the README:

> Please do not use the bug tracker for support related to operating your own site unless you are contributing code that will also benefit lobste.rs.

**Comment by vaMuchenje** [comment]
How am i supposed to even contribute when i cannot run the thing?
