### ISSUE TITLE
'rake db:schema:load' fails during installation

### ISSUE THREAD

**Issue by vaMuchenje** [jcs/lobsters#375]
Somehow this is failing and this is my trace. I am running ruby 2.3.3 and rails 5.

```
tendi@vaMuchenje:~/zg$ rake db:schema:load --trace
** Invoke db:schema:load (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke environment 
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:schema:load
-- create_table("comments", {:force=>:cascade})
   -> 0.8166s
-- add_index("comments", ["comment"], {:name=>"index_comments_on_comment", :type=>:fulltext})
   -> 1.6278s
-- add_index("comments", ["confidence"], {:name=>"confidence_idx", :using=>:btree})
   -> 0.2125s
-- add_index("comments", ["short_id"], {:name=>"short_id", :unique=>true, :using=>:btree})
   -> 0.2112s
-- add_index("comments", ["story_id", "short_id"], {:name=>"story_id_short_id", :using=>:btree})
   -> 0.2441s
-- add_index("comments", ["thread_id"], {:name=>"thread_id", :using=>:btree})
   -> 0.1998s
-- add_index("comments", ["user_id"], {:name=>"index_comments_on_user_id", :using=>:btree})
   -> 0.1561s
-- create_table("hat_requests", {:force=>:cascade})
   -> 0.3793s
-- create_table("hats", {:force=>:cascade})
   -> 0.3780s
-- create_table("hidden_stories", {:force=>:cascade})
   -> 0.4566s
-- add_index("hidden_stories", ["user_id", "story_id"], {:name=>"index_hidden_stories_on_user_id_and_story_id", :unique=>true, :using=>:btree})
   -> 0.2004s
-- create_table("invitation_requests", {:force=>:cascade})
   -> 0.3890s
-- create_table("invitations", {:force=>:cascade})
   -> 0.3908s
-- create_table("keystores", {:id=>false, :force=>:cascade})
   -> 0.3786s
-- add_index("keystores", ["key"], {:name=>"key", :unique=>true, :using=>:btree})
   -> 0.4007s
-- create_table("messages", {:force=>:cascade})
   -> 0.3794s
-- add_index("messages", ["short_id"], {:name=>"random_hash", :unique=>true, :using=>:btree})
   -> 0.2004s
-- create_table("moderations", {:force=>:cascade})
   -> 0.3448s
-- create_table("stories", {:force=>:cascade})
   -> 1.1373s
-- add_index("stories", ["created_at"], {:name=>"index_stories_on_created_at", :using=>:btree})
   -> 0.2462s
-- add_index("stories", ["description"], {:name=>"index_stories_on_description", :type=>:fulltext})
   -> 1.6940s
-- add_index("stories", ["hotness"], {:name=>"hotness_idx", :using=>:btree})
   -> 0.2011s
-- add_index("stories", ["is_expired", "is_moderated"], {:name=>"is_idxes", :using=>:btree})
   -> 0.2331s
-- add_index("stories", ["is_expired"], {:name=>"index_stories_on_is_expired", :using=>:btree})
   -> 0.1996s
-- add_index("stories", ["is_moderated"], {:name=>"index_stories_on_is_moderated", :using=>:btree})
   -> 0.2003s
-- add_index("stories", ["merged_story_id"], {:name=>"index_stories_on_merged_story_id", :using=>:btree})
   -> 0.2274s
-- add_index("stories", ["short_id"], {:name=>"unique_short_id", :unique=>true, :using=>:btree})
   -> 0.4493s
-- add_index("stories", ["story_cache"], {:name=>"index_stories_on_story_cache", :type=>:fulltext})
   -> 0.7138s
-- add_index("stories", ["title"], {:name=>"index_stories_on_title", :type=>:fulltext})
   -> 0.8139s
-- add_index("stories", ["twitter_id"], {:name=>"index_stories_on_twitter_id", :using=>:btree})
   -> 0.1663s
-- add_index("stories", ["url"], {:name=>"url", :length=>{"url"=>191}, :using=>:btree})
   -> 0.2125s
-- add_index("stories", ["user_id"], {:name=>"index_stories_on_user_id", :using=>:btree})
   -> 0.2334s
-- create_table("suggested_taggings", {:force=>:cascade})
   -> 0.3670s
-- create_table("suggested_titles", {:force=>:cascade})
   -> 0.3687s
-- create_table("tag_filters", {:force=>:cascade})
   -> 0.4002s
-- add_index("tag_filters", ["user_id", "tag_id"], {:name=>"user_tag_idx", :using=>:btree})
   -> 0.1890s
-- create_table("taggings", {:force=>:cascade})
   -> 0.3579s
-- add_index("taggings", ["story_id", "tag_id"], {:name=>"story_id_tag_id", :unique=>true, :using=>:btree})
   -> 0.2227s
-- create_table("tags", {:force=>:cascade})
   -> 0.4116s
-- add_index("tags", ["tag"], {:name=>"tag", :unique=>true, :using=>:btree})
   -> 0.1997s
-- create_table("users", {:force=>:cascade})
   -> 0.3687s
-- add_index("users", ["mailing_list_mode"], {:name=>"mailing_list_enabled", :using=>:btree})
   -> 0.2440s
-- add_index("users", ["mailing_list_token"], {:name=>"mailing_list_token", :unique=>true, :using=>:btree})
   -> 0.2003s
-- add_index("users", ["password_reset_token"], {:name=>"password_reset_token", :unique=>true, :using=>:btree})
   -> 0.2108s
-- add_index("users", ["rss_token"], {:name=>"rss_token", :unique=>true, :using=>:btree})
   -> 0.2111s
-- add_index("users", ["session_token"], {:name=>"session_hash", :unique=>true, :using=>:btree})
   -> 0.2567s
-- add_index("users", ["username"], {:name=>"username", :unique=>true, :using=>:btree})
   -> 0.1890s
-- create_table("votes", {:force=>:cascade})
   -> 0.3668s
-- add_index("votes", ["comment_id"], {:name=>"index_votes_on_comment_id", :using=>:btree})
   -> 0.2004s
-- add_index("votes", ["user_id", "comment_id"], {:name=>"user_id_comment_id", :using=>:btree})
   -> 0.2122s
-- add_index("votes", ["user_id", "story_id"], {:name=>"user_id_story_id", :using=>:btree})
   -> 0.1777s
-- create_table("comments", {:force=>:cascade})
   -> 0.1498s
-- add_index("comments", ["comment"], {:name=>"index_comments_on_comment", :type=>:fulltext})
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: near "fulltext": syntax error: CREATE fulltext INDEX "index_comments_on_comment" ON "comments" ("comment")
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:251:in `block (2 levels) in execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:250:in `block in execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:249:in `execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:725:in `add_index'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/migration.rb:849:in `block in method_missing'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/migration.rb:818:in `block in say_with_time'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/migration.rb:818:in `say_with_time'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/migration.rb:838:in `method_missing'
/home/tendi/zg/db/schema.rb:35:in `block in <top (required)>'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/schema.rb:48:in `instance_eval'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/schema.rb:48:in `define'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/schema.rb:44:in `define'
/home/tendi/zg/db/schema.rb:14:in `<top (required)>'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `load'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `block in load'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `load'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:233:in `load_schema'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:255:in `block in load_schema_current'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:304:in `block in each_current_configuration'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:303:in `each'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:303:in `each_current_configuration'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:254:in `load_schema_current'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:248:in `block (3 levels) in <top (required)>'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/tendi/.rbenv/versions/2.3.3/bin/rake:22:in `load'
/home/tendi/.rbenv/versions/2.3.3/bin/rake:22:in `<main>'
SQLite3::SQLException: near "fulltext": syntax error
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:251:in `block (2 levels) in execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:250:in `block in execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:249:in `execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:725:in `add_index'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/migration.rb:849:in `block in method_missing'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/migration.rb:818:in `block in say_with_time'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/migration.rb:818:in `say_with_time'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/migration.rb:838:in `method_missing'
/home/tendi/zg/db/schema.rb:35:in `block in <top (required)>'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/schema.rb:48:in `instance_eval'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/schema.rb:48:in `define'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/schema.rb:44:in `define'
/home/tendi/zg/db/schema.rb:14:in `<top (required)>'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `load'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `block in load'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `load'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:233:in `load_schema'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:255:in `block in load_schema_current'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:304:in `block in each_current_configuration'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:303:in `each'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:303:in `each_current_configuration'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/tasks/database_tasks.rb:254:in `load_schema_current'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.1/lib/active_record/railties/databases.rake:248:in `block (3 levels) in <top (required)>'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/tendi/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/tendi/.rbenv/versions/2.3.3/bin/rake:22:in `load'
/home/tendi/.rbenv/versions/2.3.3/bin/rake:22:in `<main>'
Tasks: TOP => db:schema:load
```

**Comment by jcs** [comment]
The code requires MySQL/MariaDB with fulltext indexing, which SQLite doesn't handle.

**Comment by vaMuchenje** [comment]
I do have MySQL installed and I have setup the database and database.yml file in a previous step. What would you recommend? Use the development specifications in database.yml for development in test as well? Or is there a way I can disable the need for fulltext indexing for my test environment which uses SQLite?

**Comment by jcs** [comment]
Making separate development and test databases in MySQL would probably be the way to go, that's how I do it on my laptop.

**Comment by vaMuchenje** [comment]
Thank you very much. I will do that. Thanks a lot. Will close this.
